### ISSUE TITLE
Labels ID Suggestion

### ISSUE THREAD

**Issue by jorgealmerio** [msweier/QGIS-Profile-from-Points-Plugin#2]
Hi, congratulations for the plugin.

I suggest to draw labels (Point ID selected field) for each point data on the Profile plot as we can find where it is on plan.

If you want I did it for you, just insert it after line 141 of refreshPlot function on "profileFromPoints_dialog.py"

```
#Plot id labels
for i,linha in enumerate(np.array(self.values[2])):
    id=self.values[2][i]
    dist=self.values[0][i]
    z=self.values[1][i]
    self.axes.annotate(id,(dist,z))
```

**Comment by msweier** [comment]
Good suggestion, I added it as an option.  When plotting many points it gets difficult to see.  Will be included in the new version.
